runpl:
	./annotate-uproc.pl6 --pfam-out=uproc-out.pfam --kegg-out=uproc-out.kegg --pfam-desc=pfam_to_domain --kegg-desc=kegg_to_desc --out=combined.out

run:
	./annotate_uproc.py --pfam_out=uproc-out.pfam --kegg_out=uproc-out.kegg --pfam_desc=pfam_to_domain --kegg_desc=kegg_to_desc --out=combined.out
